trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadPipelineArtifact@1
  inputs:
    artifactName: base
    targetPath: $(Build.SourcesDirectory)/base

- task: CMake@1
  inputs:
    cmakeArgs: '..'

- task: CMake@1
  inputs:
    cmakeArgs: '--build . --config Debug --target install'
