trigger:
- master

pr:
- master

variables:
  CLICOLOR_FORCE: 1 # used by tools

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadPipelineArtifact@1
  inputs:
    buildType: 'specific'
    project: 'base'
    definition: 2
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    artifactName: 'base-windows'
    targetPath: $(Build.SourcesDirectory)/base

- task: CMake@1
  inputs:
    cmakeArgs: '.. -DCOLOR=1 -DCMAKE_PREFIX_PATH=base -DCMAKE_INSTALL_PREFIX=install'

- task: CMake@1
  inputs:
    cmakeArgs: '--build . --config Debug --target install'

- task: CmdLine@2
  displayName: 'Run tests'
  continueOnError: true
  inputs:
    script: |
      ctest -T Test -C Debug
    workingDirectory: $(System.DefaultWorkingDirectory)/build

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'cTest'
    testResultsFiles: '**/Test.xml'
    testRunTitle: 'Test results for CTest'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'base-windows-x64'
    targetPath: 'artifacts'
    path: $(System.DefaultWorkingDirectory)/build/install
